#pragma once
#include "Window.h"
#include "Math.h"
#include "Vector2.h"
#include "Figure.h"
#include "Image.h"

#include "Input.h"
#include "D2DRenderer.h"
#include "ImageManager.h"
#include "ObjPool.h"
#include "RenderPool.h"
#include "SceneManager.h"
#include "TestScene.h"
#include "TestScene1.h"